### ISSUE TITLE
Inside the editor, radio buttons look off

### ISSUE THREAD

**Issue by janboddez** [bgardner/powder#3]
Playing around with different block themes, including Powder, I noticed something odd about the radio buttons in one of my blocks' placeholder element:
<img src="https://user-images.githubusercontent.com/8428432/196553251-7f2c8cf9-376d-42d2-b568-e4f1b24e2d9b.png" width="303">
With the other themes so far these looked "normal." (And if I switch back, they look normal again.)
<img src="https://user-images.githubusercontent.com/8428432/196552881-df1a7831-2eb1-4e19-bb78-1675f510f29b.png" width="228">
I think the following CSS is to blame:
```
input[type="checkbox"],
input[type="image"],
input[type="radio"] {
	width: auto;
}
```
Now, I can fix this in my own code, but I was thinking maybe you're simply accidentally resetting a few too many styles here?

**Comment by bgardner** [comment]
@janboddez Curious what change you would suggest here.

**Comment by janboddez** [comment]
Well, what I do now is again override these in my own (i.e., the plugin's) editor stylesheet, with whatever hardcoded values are in WP core (I believe a 24px width and height on smaller screens, and 20px for `min-width: 600px`).

But I was wondering why a theme would explicitly set widths, and especially `width: auto`, for input controls at all.

I mean, wouldn't this also "mess up," e.g., any forms on the front end? ("Mess up" meaning that checkboxes would no longer be square, etc. Which doesn't seem like something you'd want?) Unless these style are editor-only: in that case I wonder why one wouldn't just go with core's default.

Wondering if it wouldn't be more "transparent" to just drop these rules completely.

Just found the core CSS rules, btw: https://github.com/WordPress/WordPress/blob/bbb40de012670768a525193639c0d5e4ea932df7/wp-includes/css/dist/components/style.css#L2607
