### ISSUE TITLE
Typo in pattern title "Testimonial grid-dark"

### ISSUE THREAD

**Issue by luisrull** [bgardner/powder#39]
In patterns/testimonials-grid-dark.php
and
patterns/testimonials-grid.php

* Title: Testimonials in _gird_ view

should be 

* Title: Testimonials in _grid_ view

**Comment by bgardner** [comment]
Thanks @luisrull!

**Comment by luisrull** [comment]
You are welcome.
BTW, it's almost translated into es_ES https://translate.wordpress.org/locale/es/default/wp-themes/powder/
