### ISSUE TITLE
Pin the footer to the bottom

### ISSUE THREAD

**Issue by devhaozi** [bgardner/powder#71]
Is there an easy way to pin the footer to the bottom when no content?

![image](https://github.com/user-attachments/assets/8e87d5d5-bac5-4ad4-b701-38d47983645b)

Current feasible way I have found is to set a larger height for the main container (such as `height: 80vh`), but this will cause extra scroll bars when the browser window is small.

**Comment by bgardner** [comment]
There are probably some caveats here, but this custom CSS seems like it could work:

```
.error404 .site-footer {
	bottom: 0;
	position: absolute;
	width: 100%;
}
```

**Comment by bgardner** [comment]
Closing this as it’s not really an issue, and a solution was provided.
